// File generated by FlutterFire CLI and sanitized for source control.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
  );
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
  );
  static const String _windowsApiKey = String.fromEnvironment(
    'FIREBASE_WINDOWS_API_KEY',
  );

  static String _requireApiKey(String value, String defineName) {
    if (value.isEmpty) {
      throw UnsupportedError(
        'Missing Firebase API key: $defineName. '
        'Run with --dart-define=$defineName=<value>.',
      );
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _requireApiKey(_webApiKey, 'FIREBASE_WEB_API_KEY'),
    appId: '1:251272354309:web:5de5887f1f52d07b249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    authDomain: 'frc-staff-juwon-20260226.firebaseapp.com',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requireApiKey(_androidApiKey, 'FIREBASE_ANDROID_API_KEY'),
    appId: '1:251272354309:android:6defae0c4768a0c7249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requireApiKey(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
    appId: '1:251272354309:ios:6c43da9c76524875249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
    iosBundleId: 'com.example.fishingRodCalculator',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _requireApiKey(_iosApiKey, 'FIREBASE_IOS_API_KEY'),
    appId: '1:251272354309:ios:6c43da9c76524875249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
    iosBundleId: 'com.example.fishingRodCalculator',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _requireApiKey(
      _windowsApiKey.isEmpty ? _webApiKey : _windowsApiKey,
      _windowsApiKey.isEmpty
          ? 'FIREBASE_WEB_API_KEY'
          : 'FIREBASE_WINDOWS_API_KEY',
    ),
    appId: '1:251272354309:web:43e2d6f9a8a9c5d5249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    authDomain: 'frc-staff-juwon-20260226.firebaseapp.com',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );
}
