// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXaLe0_XhSPsy2ZDl70wAfb_1U-8F8Bns',
    appId: '1:251272354309:web:5de5887f1f52d07b249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    authDomain: 'frc-staff-juwon-20260226.firebaseapp.com',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxbgbWLScjBLUTnmO5njPDUXMzokR0HmA',
    appId: '1:251272354309:android:6defae0c4768a0c7249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYvE86BX9fxXAyjX_LXXYPIncix7G_Pg',
    appId: '1:251272354309:ios:6c43da9c76524875249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
    iosBundleId: 'com.example.fishingRodCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrYvE86BX9fxXAyjX_LXXYPIncix7G_Pg',
    appId: '1:251272354309:ios:6c43da9c76524875249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
    iosBundleId: 'com.example.fishingRodCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXaLe0_XhSPsy2ZDl70wAfb_1U-8F8Bns',
    appId: '1:251272354309:web:43e2d6f9a8a9c5d5249a6c',
    messagingSenderId: '251272354309',
    projectId: 'frc-staff-juwon-20260226',
    authDomain: 'frc-staff-juwon-20260226.firebaseapp.com',
    storageBucket: 'frc-staff-juwon-20260226.firebasestorage.app',
  );
}
